# Generated by Django 6.0.2 on 2026-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='expense_type',
            field=models.CharField(choices=[('business', 'Business Expense'), ('non_business', 'Non-Business Expense')], default='non_business', max_length=20, verbose_name='Expense Type'),
        ),
    ]
