# Generated by Django 6.0.2 on 2026-08-24 18:24

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenseitem_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='account',
            field=models.ForeignKey(blank=True, default=expenses.models.get_default_cash_account, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.account', verbose_name='Account / Payment Method'),
        ),
    ]
