# Generated by Django 6.0.2 on 2026-03-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='from_bank_name',
            field=models.CharField(blank=True, help_text='Required if From Account is Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='to_bank_name',
            field=models.CharField(blank=True, help_text='Required if To Account is Bank', max_length=100, null=True),
        ),
    ]
