# Generated by Django 6.0.2 on 2026-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_accounttransfer_from_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='from_mobile_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], help_text='Required if From Account is Mobile Banking', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accounttransfer',
            name='to_mobile_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], help_text='Required if To Account is Mobile Banking', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Required if Payment Method is Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=10, null=True),
        ),
    ]
