# Generated by Django 6.0.2 on 2026-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_profit_to_coadmins', models.BooleanField(default=False, help_text='If unchecked, profit calculations and profit columns are only visible to Superusers (Main Admin).', verbose_name='Allow Co-Admins & Staff to view Profit data')),
            ],
            options={
                'verbose_name': 'Profit Visibility Setting',
                'verbose_name_plural': 'Profit Visibility Settings',
            },
        ),
    ]
