# Generated by Django 6.0.2 on 2026-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('import_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unit'), ('meter', 'Meter')], default='unit', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductValuation',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory Valuation Report',
                'verbose_name_plural': 'Inventory Valuation Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
    ]
