# Generated by Django 6.0.2 on 2026-03-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_importer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
    ]
