# Generated by Django 6.0.2 on 2026-04-08 21:42

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Daily Activity & Report',
                'verbose_name_plural': 'Daily Activity & Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
