"""
Django settings for companys project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from pathlib import Path

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-g+r)##hxjm(h_6-6xbp7#otuae^%pa)x)&+oviwabfouzk()4m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    'dashboard.apps.DashboardConfig',
    'dashboard.apps.CustomAdminConfig',
    'inventory',
    'sales',
    'expenses',
    'reports',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

UNFOLD = {
    "SITE_HEADER": "Global Trade Management",
    "SITE_TITLE": "Global Trade",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "RELATED_MODAL_ACTIVE": True,
    "COLORS": {
        "primary": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Main Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Inventory Management",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/inventory/product/",
                    },
                    {
                        "title": "Valuation Report",
                        "icon": "analytics",
                        "link": "/admin/inventory/productvaluation/",
                    },
                ],
            },
            {
                "title": "Sales & Customers",
                "separator": True,
                "items": [
                    {
                        "title": "Customers",
                        "icon": "person",
                        "link": "/admin/sales/customer/",
                    },
                    {
                        "title": "Sales Orders",
                        "icon": "shopping_cart",
                        "link": "/admin/sales/sale/",
                    },
                    {
                        "title": "Payments",
                        "icon": "payments",
                        "link": "/admin/sales/payment/",
                    },
                    {
                        "title": "Returns",
                        "icon": "assignment_return",
                        "link": "/admin/sales/productreturn/",
                    },
                ],
            },
            {
                "title": "Finance & Expenses",
                "separator": True,
                "items": [
                    {
                        "title": "Daily Expenses",
                        "icon": "receipt_long",
                        "link": "/admin/expenses/dailyexpense/",
                    },
                    {
                        "title": "Product Orders (Suppliers)",
                        "icon": "local_shipping",
                        "link": "/admin/expenses/productorder/",
                    },
                    {
                        "title": "Account Transfers",
                        "icon": "account_balance",
                        "link": "/admin/expenses/accounttransfer/",
                    },
                ],
            },
            {
                "title": "HR & Payroll",
                "separator": True,
                "items": [
                    {
                        "title": "Employees",
                        "icon": "badge",
                        "link": "/admin/expenses/employee/",
                    },
                    {
                        "title": "Salary Transactions",
                        "icon": "monetization_on",
                        "link": "/admin/expenses/salarytransaction/",
                    },
                ],
            },
            {
                "title": "Reports",
                "separator": True,
                "items": [
                    {
                        "title": "Daily Activity",
                        "icon": "history_ed",
                        "link": "/admin/reports/dailyactivity/",
                    },
                ],
            },
            {
                "title": "System Settings",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "manage_accounts",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
            {
                "title": "System Tools",
                "separator": True,
                "items": [
                    {
                        "title": "Download Data Backup",
                        "icon": "download_for_offline",
                        "link": "/admin/backup/download/",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'companys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'companys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']
