# Generated by Django 6.0.2 on 2026-03-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturn',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_check', 'Bank Check'), ('bank_transaction', 'Bank Transaction'), ('mobile_banking', 'Mobile Banking')], default='cash', max_length=20),
        ),
    ]
