# Generated by Django 6.0.2 on 2026-04-08 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
