# Generated by Django 6.0.2 on 2026-04-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_sale_sale_cheque_date_sale_cheque_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cheque_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cheque_number',
        ),
    ]
