# Generated by Django 6.0.2 on 2026-03-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productreturn_amount_refunded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('bank_check', 'Bank Check'), ('bank_transaction', 'Bank Transaction'), ('mobile_banking', 'Mobile Banking')], default='cash', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_banking_type', models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced')], default='CLEARED', max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('clearance_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_refunds', to='sales.customer')),
            ],
        ),
    ]
