# Generated by Django 6.0.2 on 2026-03-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='real_rate_at_that_time',
        ),
    ]
