# Generated by Django 6.0.2 on 2026-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_real_rate_at_that_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_profit',
        ),
    ]
