# Generated by Django 6.0.2 on 2026-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='condition_notes',
            field=models.CharField(blank=True, help_text='e.g., Courier details, delivery conditions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_conditional',
            field=models.BooleanField(default=False, verbose_name='Conditional Sale (Payment on Delivery)'),
        ),
    ]
