# Generated by Django 6.0.2 on 2026-03-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_condition_notes_sale_is_conditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transport_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
