# Generated by Django 6.0.2 on 2026-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_transport_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=10, null=True),
        ),
    ]
