# Generated by Django 6.0.2 on 2026-08-10 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_profit_sale_purchase_price_at_that_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
