# Generated by Django 6.0.2 on 2026-03-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_total_due_sale_amount_paid_sale_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.customer'),
        ),
    ]
