# Generated by Django 6.0.2 on 2026-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_productreturn_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_is_withdrawn',
            field=models.BooleanField(default=False, verbose_name='Is Check Withdrawn?'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_check', 'Bank Check'), ('bank_transaction', 'Bank Transaction'), ('mobile_banking', 'Mobile Banking')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='check_is_withdrawn',
            field=models.BooleanField(default=False, verbose_name='Is Check Withdrawn?'),
        ),
        migrations.AddField(
            model_name='sale',
            name='mobile_banking_type',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_check', 'Bank Check'), ('bank_transaction', 'Bank Transaction'), ('mobile_banking', 'Mobile Banking')], default='cash', max_length=20),
        ),
    ]
